### ISSUE TITLE
Mod defines indescriptive mod id in fabric.mod.json

### ISSUE THREAD

**Issue by Geolykt** [chimericdream/shelf-storage#8]
See https://github.com/chimericdream/shelf-storage/blob/main/src/main/resources/fabric.mod.json#L3

Not absolutely pressing but I anticipate that it may cause issues with other mods that may accidentally do the same

**Comment by chimericdream** [comment]
Yeeeaaaaahhhhhh. I totally put that there as an easter egg... on purpose. Yeah. Would you believe that I'm actually a professional software developer? :-p

I will get this fixed in the next update.
